### ISSUE TITLE
m30pm libraries not found when running m30pm CLI app from compiled binary

### ISSUE THREAD

**Issue by capsulecorplab** [Mach30/m30pm#48]
![Screenshot from 2024-09-15 11-49-48](https://github.com/user-attachments/assets/849b0573-20eb-4d14-8512-4230b90b93c3)

**Comment by j-simmons-phd** [comment]
See https://github.com/oclif/oclif/issues/183#issuecomment-1933104981 for fix.

**Comment by capsulecorplab** [comment]
Actually, this appears to be a completely separate issue; the compiled binaries aren't properly calling the m30pm-lib-common library, as the same error occurs for when trying to create a project
![Screenshot from 2024-09-24 19-09-13](https://github.com/user-attachments/assets/4ae02e7b-4c71-487a-8a67-158717242f14)

**Comment by capsulecorplab** [comment]
Otherwise, the help text appears when called from dev.js
![Screenshot from 2024-09-24 19-14-45](https://github.com/user-attachments/assets/9b080c25-6f9c-4622-81ff-37978722cdcb)

**Comment by j-simmons-phd** [comment]
Fascinating...  Time for more digging into Oclif things, I guess.

**Comment by capsulecorplab** [comment]
Resolved as per f1094756 ![Screenshot from 2024-11-13 16-05-52](https://github.com/user-attachments/assets/1434a5e8-9b51-491c-ab12-7ba3ca55fbfc)

**Comment by capsulecorplab** [comment]
Re-opening, has not yet been resolved in main branch

**Comment by capsulecorplab** [comment]
Re-opening, as I seemed to have merged the PR for packaging from tarball, instead of packaging from debian - whereby issue still persists.
