### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by j-simmons-phd** [Mach30/m30pm#9]
Having started to mock up the cli and its commands, I can seen I will get tired of typing out "~~m30mlTools~~ m30pm make". The ~~m30mlTools~~ m30pm is just a little longer than I want to type out every time I use it. Plus, I want to separate out the logic from the cli (so we can use the logic in later tools like desktop gui and web based).  So, I am thinking about the following project refactor:

- ~~m30ml~~ m30pm = the cli tools (originally m30mlTools)
- ~~m30mlLang~~ m30ml = the language definition/architecture (originally m30ml)
- ~~m30mlLib~~ m30pmlib = the logic of manipulating ~~m30mlLang~~ m30ml content, abstracted away from files so it can be equally applied to data on file system or in other data stores (possibly even working directly against repos by url??), this is a new project

This would let users run cli commands with just "~~m30ml~~ m30pm make", etc. And it gives us the lib for including in other projects.

This issue should be closed by an update to README or m30pm spec

**Comment by j-simmons-phd** [comment]
Two useful links for this work:
- https://bugfender.com/blog/how-to-create-an-npm-package/
- https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by capsulecorplab** [comment]
I'm on the fence about using m30mlLang to refer to the language definition/architecture, since "language" is already a part of the acronym. Though, I can see the appeal with a shorter name for the cli tool... Might I suggest `m30pm` (Mach30 project/package manager) as an alternative name for the name of the cli tool?

**Comment by j-simmons-phd** [comment]
I see what you mean about the language def/arch (please enter your PIN number).  @m30-css was suggesting we consider a name for the tool that was more expressive (e.g. how we named Sliderule).  That being said, neither of us have landed on something cool and not already taken.  

So, I would be good with m30pm for the cli tool until something better comes along.

**Comment by j-simmons-phd** [comment]
The required changes in project and conversations have all happened.
